create table if not exists public.leaderboard_entries (
  id bigint generated by default as identity primary key,
  name text not null,
  kills integer not null,
  time_seconds numeric(10,1) not null,
  created_at timestamptz not null default now(),
  constraint leaderboard_name_len check (char_length(name) between 1 and 24),
  constraint leaderboard_name_chars check (name ~ '^[A-Za-z0-9 _.\-]+$'),
  constraint leaderboard_kills_range check (kills between 0 and 1000000),
  constraint leaderboard_time_range check (time_seconds >= 0 and time_seconds <= 86400)
);

create index if not exists leaderboard_entries_sort_idx
  on public.leaderboard_entries (kills desc, time_seconds asc, id asc);

create or replace function public.contains_blocked_name(input text)
returns boolean
language sql
immutable
as $$
  select regexp_replace(lower(coalesce(input, '')), '[^a-z0-9]', '', 'g')
    ~ '(fuck|shit|bitch|cunt|nigg|faggot|whore|slut|dick|cock|pussy|asshole|motherfucker)';
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'leaderboard_name_clean'
      and conrelid = 'public.leaderboard_entries'::regclass
  ) then
    alter table public.leaderboard_entries
      add constraint leaderboard_name_clean
      check (not public.contains_blocked_name(name));
  end if;
end $$;

alter table public.leaderboard_entries enable row level security;

drop policy if exists leaderboard_select_all on public.leaderboard_entries;
create policy leaderboard_select_all
on public.leaderboard_entries
for select
to anon
using (true);

drop policy if exists leaderboard_insert_anon on public.leaderboard_entries;
create policy leaderboard_insert_anon
on public.leaderboard_entries
for insert
to anon
with check (true);
